var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,g="undefined"!=typeof WorkerGlobalScope,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,ca=Object.assign({},f),da=[],ea="./this.program",fa=(a,b)=>{throw b;},n="",ha,p;
if(ba){var fs=require("fs");require("path");n=__dirname+"/";p=a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||g)g?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),n=n.startsWith("blob:")?
"":n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1),g&&(p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=async a=>{if(ia(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};f.print||console.log.bind(console);var r=f.printErr||console.error.bind(console);Object.assign(f,ca);ca=null;f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);var ja=f.wasmBinary,ka,t=!1,la,v,w,ma,na,x,y,pa,z,qa=a=>a.startsWith("data:application/octet-stream;base64,"),ia=a=>a.startsWith("file://"),ra=[],sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();ra.unshift(a)}var B=0,C=null;
function wa(a){f.onAbort?.(a);a="Aborted("+a+")";r(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa;async function ya(a){if(!ja)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==xa&&ja)a=new Uint8Array(ja);else if(p)a=p(a);else throw"both async and sync fetching of the wasm failed";return a}
async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}async function Aa(a){var b=xa;if(!(ja||"function"!=typeof WebAssembly.instantiateStreaming||qa(b)||ia(b)||ba))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return za(b,a)}
class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ca=a=>{for(;0<a.length;)a.shift()(f)},Da=f.noExitRuntime||!0,Ka=(a,b)=>{Ea=a;Fa=b;if(D)if(Ga||=!0,0==a)E=function(){setTimeout(F,Math.max(0,Ha+b-performance.now())|0)};else if(1==a)E=function(){Ia(F)};else if(2==a){if("undefined"==typeof Ja)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ja=d=>{c.push(d);if(g){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ja=setImmediate;E=function(){Ja(F)}}},La=a=>{la=a;Da||(f.onExit?.(a),t=!0);fa(a,new Ba(a))},Ma=a=>{la=a;La(a)},Na=a=>{a instanceof Ba||"unwind"==a||fa(1,a)},Oa=()=>{if(!Da)try{var a=la;la=a;La(a)}catch(b){Na(b)}},Xa=(a,b,c,d,e)=>{function k(){return h<Pa?(Oa(),!1):!0}D=a;Qa=d;var h=Pa;Ga=!1;F=function(){if(!t)if(0<Ra.length){var l=Ra.shift();l.bd(l.Tc);if(Sa){var m=Sa,q=0==m%1?m-1:Math.floor(m);Sa=l.Vc?q:(8*m+(q+.5))/
9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=Sa??0,q=Ta.$c??0,m?m<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));k()&&setTimeout(F,0)}else if(k())if(Ua=Ua+1|0,1==Ea&&1<Fa&&0!=Ua%Fa)E();else{0==Ea&&(Ha=performance.now());a:if(!t){for(l of Va)if(!1===l())break a;if(!t)try{a(),Oa()}catch(u){Na(u)}for(m of Wa)m()}k()&&E()}};e||(b&&0<b?Ka(0,1E3/b):Ka(1,1),E());if(c)throw"unwind";},Ga=!1,E=null,Pa=0,D=null,Qa=0,Ea=0,Fa=0,Ua=0,Ra=[],Va=[],Wa=[];
function Ya(){E=null;Pa++}var G=0;function Ia(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var Ta={},Ha,F,Ja,Sa;function Za(a){var b=H.Sb[a];b.target.removeEventListener(b.Rb,b.xc,b.Tb);H.Sb.splice(a,1)}function $a(){if(navigator.userActivation?navigator.userActivation.isActive:H.jc&&H.Kc.hc){var a=H.Xb;H.Xb=[];for(var b of a)b.mc(...b.tc)}}
function I(a){if(!a.target)return-4;if(a.Ub)a.xc=function(c){++H.jc;H.Kc=a;$a();a.Vb(c);$a();--H.jc},a.target.addEventListener(a.Rb,a.xc,a.Tb),H.Sb.push(a);else for(var b=0;b<H.Sb.length;++b)H.Sb[b].target==a.target&&H.Sb[b].Rb==a.Rb&&Za(b--);return 0}function ab(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={Uc:0,cd:0,kc:0,ec:0,qc:0,oc:0,ic:0,Yc:0,hd:0,Xc:0,ad:0,lc:0,qd:0,nc:0,ed(a,b,c){v.set(v.subarray(b,b+c),a)},kd(){for(;H.Sb.length;)Za(H.Sb.length-1);H.Xb=[]},jc:0,Xb:[],Wc(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var e of H.Xb)if(e.mc==a&&d(e.tc,c))return;H.Xb.push({mc:a,Bc:b,tc:c});H.Xb.sort((k,h)=>k.Bc<h.Bc)},md(a){H.Xb=H.Xb.filter(b=>b.mc!=a)},Sb:[],ld:(a,b)=>{for(var c=0;c<H.Sb.length;++c)H.Sb[c].target!=a||b&&b!=H.Sb[c].Rb||
Za(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b=NaN)=>{var c=w,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&bb)return bb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var h=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|h:(e&7)<<18|k<<12|h<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},L,M=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.charCodeAt(k);if(55296<=h&&57343>=h){var l=a.charCodeAt(++k);h=
65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-e},eb=(a,b,c,d,e,k)=>{H.ic||(H.ic=N(256));a={target:K(a),Rb:k,Ub:d,Vb:(h=event)=>{var l=h.target.id?h.target.id:"",m=H.ic;M(ab(h.target),m+0,128);M(l,m+128,128);L.get(d)(e,m,b)&&h.preventDefault()},Tb:c};return I(a)},fb=(a,b,c,d,
e,k)=>{H.kc||(H.kc=N(160));a={target:K(a),Rb:k,Ub:d,Vb:h=>{var l=H.kc;z[l>>3]=h.timeStamp;var m=l>>2;x[m+2]=h.location;v[l+12]=h.ctrlKey;v[l+13]=h.shiftKey;v[l+14]=h.altKey;v[l+15]=h.metaKey;v[l+16]=h.repeat;x[m+5]=h.charCode;x[m+6]=h.keyCode;x[m+7]=h.which;M(h.key||"",l+32,32);M(h.code||"",l+64,32);M(h.char||"",l+96,32);M(h.locale||"",l+128,32);L.get(d)(e,l,b)&&h.preventDefault()},Tb:c};return I(a)},gb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;x[d+2]=b.screenX;x[d+3]=b.screenY;x[d+4]=b.clientX;x[d+
5]=b.clientY;v[a+24]=b.ctrlKey;v[a+25]=b.shiftKey;v[a+26]=b.altKey;v[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;x[d+8]=b.movementX;x[d+9]=b.movementY;a=db(c);x[d+10]=b.clientX-(a.left|0);x[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{H.ec||(H.ec=N(64));a=K(a);return I({target:a,hc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Rb:k,Ub:d,Vb:(h=event)=>{gb(H.ec,h,a);L.get(d)(e,H.ec,b)&&h.preventDefault()},Tb:c})},hb=(a,b,c,d,e)=>{H.lc||(H.lc=N(257));return I({target:a,Rb:e,Ub:d,Vb:(k=
event)=>{var h=H.lc,l=document.pointerLockElement||document.Zb||document.sc||document.rc;v[h]=!!l;var m=l?.id||"";M(ab(l),h+1,128);M(m,h+129,128);L.get(d)(20,h,b)&&k.preventDefault()},Tb:c})},ib=(a,b,c,d,e)=>I({target:a,Rb:e,Ub:d,Vb:(k=event)=>{L.get(d)(38,0,b)&&k.preventDefault()},Tb:c}),jb=(a,b,c,d)=>{H.oc||(H.oc=N(36));a=K(a);return I({target:a,Rb:"resize",Ub:d,Vb:(e=event)=>{if(e.target==a){var k=document.body;if(k){var h=H.oc;x[h>>2]=0;x[h+4>>2]=k.clientWidth;x[h+8>>2]=k.clientHeight;x[h+12>>
2]=innerWidth;x[h+16>>2]=innerHeight;x[h+20>>2]=outerWidth;x[h+24>>2]=outerHeight;x[h+28>>2]=pageXOffset|0;x[h+32>>2]=pageYOffset|0;L.get(d)(10,h,b)&&e.preventDefault()}}},Tb:c})},kb=(a,b,c,d,e,k)=>{H.nc||(H.nc=N(1552));a=K(a);return I({target:a,hc:"touchstart"==k||"touchend"==k,Rb:k,Ub:d,Vb:h=>{var l={},m=h.touches;for(var q of m)q.yc=q.Ac=0,l[q.identifier]=q;for(var u of h.changedTouches)u.yc=1,l[u.identifier]=u;for(var oa of h.targetTouches)l[oa.identifier].Ac=1;m=H.nc;z[m>>3]=h.timeStamp;v[m+
12]=h.ctrlKey;v[m+13]=h.shiftKey;v[m+14]=h.altKey;v[m+15]=h.metaKey;q=m+16;u=db(a);oa=0;for(let A of Object.values(l))if(l=q>>2,x[l]=A.identifier,x[l+1]=A.screenX,x[l+2]=A.screenY,x[l+3]=A.clientX,x[l+4]=A.clientY,x[l+5]=A.pageX,x[l+6]=A.pageY,v[q+28]=A.yc,v[q+29]=A.Ac,x[l+8]=A.clientX-(u.left|0),x[l+9]=A.clientY-(u.top|0),q+=48,31<++oa)break;x[m+8>>2]=oa;L.get(d)(e,m,b)&&h.preventDefault()},Tb:c})},P,lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,h)=>b.drawElementsInstancedANGLE(c,d,e,k,h))},mb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},nb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ob=a=>
{a.Zc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},pb=a=>{a.dd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},qb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},rb=1,Q=[],R=[],sb=[],S=[],T=[],U=[],tb=[],ub=[],V=[],vb={},wb=4,xb=0,yb=a=>{for(var b=rb++,c=a.length;c<b;c++)a[c]=null;return b},X=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=P[c](),h=k&&yb(d);k?(k.name=h,d[h]=k):W||=1282;x[b+4*e>>2]=h}},Ab=(a,b)=>{a.Zb||(a.Zb=a.getContext,a.getContext=function(d,e){e=a.Zb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.zc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
zb(c,b):0},zb=(a,b)=>{var c=yb(ub),d={handle:c,attributes:b,version:b.zc,fc:a};a.canvas&&(a.canvas.Sc=d);ub[c]=d;("undefined"==typeof b.wc||b.wc)&&Bb(d);return c},Bb=a=>{a||=Y;if(!a.Pc){a.Pc=!0;var b=a.fc;b.Qc=b.getExtension("WEBGL_multi_draw");b.Oc=b.getExtension("EXT_polygon_offset_clamp");b.Nc=b.getExtension("EXT_clip_control");b.Rc=b.getExtension("WEBGL_polygon_mode");lb(b);mb(b);nb(b);ob(b);pb(b);2<=a.version&&(b.vc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.vc)b.vc=
b.getExtension("EXT_disjoint_timer_query");qb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},W,Y,Cb=(a,b,c,d,e,k)=>{a={target:K(a),Rb:k,Ub:d,Vb:(h=event)=>{L.get(d)(e,0,b)&&h.preventDefault()},Tb:c};I(a)},Db=(a,b,c,d)=>{H.qc||(H.qc=N(96));return I({target:a,hc:!0,Rb:"wheel",Ub:d,Vb:(e=event)=>{var k=H.qc;gb(k,e,a);z[k+64>>3]=e.deltaX;z[k+72>>3]=e.deltaY;z[k+80>>3]=e.deltaZ;x[k+88>>2]=e.deltaMode;L.get(d)(9,k,b)&&e.preventDefault()},Tb:c})},Eb=["default","low-power",
"high-performance"],Fb=[],Gb=()=>{var a=qb(P);return a=a.concat(a.map(b=>"GL_"+b))},Hb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W||=1282;return}c=Gb().length;break;case 33307:case 33308:if(2>Y.version){W||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W||=
1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:W||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W||=1280;r(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:W||=1280;r(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}x[b>>2]=c}else W||=1281},Ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Jb=a=>{var b=Ib(a)+1,c=N(b);c&&M(a,c,b);return c},Kb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Lb=a=>{a-=5120;return 0==a?v:1==a?w:2==a?ma:4==a?x:6==a?pa:5==a||28922==a||28520==a||30779==a||30782==
a?y:na},Nb=a=>{var b=Ib(a)+1,c=Mb(b);M(a,c,b);return c},Qb=a=>{var b=Ob();a();Pb(b)};f.requestAnimationFrame=Ia;f.pauseMainLoop=Ya;f.resumeMainLoop=function(){Pa++;var a=Ea,b=Fa,c=D;D=null;Xa(c,0,!1,Qa,!0);Ka(a,b);E()};f.preMainLoop&&Va.push(f.preMainLoop);f.postMainLoop&&Wa.push(f.postMainLoop);for(var Rb=0;32>Rb;++Rb)Fb.push(Array(Rb));
var Yb={ab:()=>wa(""),mb:()=>{Ya();D=null},O:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ja:(a,b,c)=>{a=K(a);if(!a)return-4;a=db(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},nb:()=>performance.now(),Wa:(a,b)=>{function c(d){L.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:()=>{wa("OOM")},Q:(a,b,c,d)=>eb(a,b,c,d,12,"blur"),L:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>eb(a,b,c,d,13,"focus"),$:(a,b,c,d)=>fb(a,b,c,d,2,"keydown"),
Z:(a,b,c,d)=>fb(a,b,c,d,1,"keypress"),_:(a,b,c,d)=>fb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=L.get(a);Xa(a,b,c)},w:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),ea:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),ga:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Zb||document.body.sc||document.body.rc))return-1;a=K(a);if(!a)return-4;hb(a,b,c,d,"mozpointerlockchange");
hb(a,b,c,d,"webkitpointerlockchange");hb(a,b,c,d,"mspointerlockchange");return hb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Zb||document.body.sc||document.body.rc))return-1;a=K(a);if(!a)return-4;ib(a,b,c,d,"mozpointerlockerror");ib(a,b,c,d,"webkitpointerlockerror");ib(a,b,c,d,"mspointerlockerror");return ib(a,b,c,d,"pointerlockerror")},W:(a,b,c,d)=>jb(a,b,c,d),U:(a,b,c,d)=>kb(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>kb(a,b,c,d,23,"touchend"),
X:(a,b,c,d)=>kb(a,b,c,d,24,"touchmove"),Y:(a,b,c,d)=>kb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{Cb(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Cb(a,b,c,d,32,"webglcontextrestored");return 0},aa:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Db(a,b,c,d):-1:-4,Ja:(a,b)=>{var c=b>>2;b={alpha:!!v[b+0],depth:!!v[b+1],stencil:!!v[b+2],antialias:!!v[b+3],premultipliedAlpha:!!v[b+4],preserveDrawingBuffer:!!v[b+5],powerPreference:Eb[x[c+2]],failIfMajorPerformanceCaveat:!!v[b+12],zc:x[c+4],gd:x[c+
5],wc:v[b+24],Mc:v[b+25],jd:x[c+7],nd:v[b+32]};a=K(a);return!a||b.Mc?0:Ab(a,b)},qa:(a,b)=>{a=ub[a];b=b?J(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&lb(P);"OES_vertex_array_object"==b&&mb(P);"WEBGL_draw_buffers"==b&&nb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&ob(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&pb(P);"WEBGL_multi_draw"==b&&(P.Qc=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.Oc=P.getExtension("EXT_polygon_offset_clamp"));
"EXT_clip_control"==b&&(P.Nc=P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.Rc=P.getExtension("WEBGL_polygon_mode"));return!!a.fc.getExtension(b)},ya:a=>{Y=ub[a];f.ctx=P=Y?.fc;return!a||P?0:-5},p:a=>P.activeTexture(a),G:(a,b)=>{P.attachShader(R[a],U[b])},a:(a,b)=>{35051==a?P.uc=b:35052==a&&(P.Yb=b);P.bindBuffer(a,Q[b])},j:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},f:(a,b)=>{P.bindFramebuffer(a,sb[b])},Ia:(a,b)=>{P.bindRenderbuffer(a,S[b])},o:(a,b)=>{P.bindSampler(a,V[b])},g:(a,b)=>{P.bindTexture(a,
T[b])},M:a=>{P.bindVertexArray(tb[a])},t:(a,b,c,d)=>P.blendColor(a,b,c,d),u:(a,b)=>P.blendEquationSeparate(a,b),v:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),tb:(a,b,c,d,e,k,h,l,m,q)=>P.blitFramebuffer(a,b,c,d,e,k,h,l,m,q),La:(a,b,c,d)=>{2<=Y.version?c&&b?P.bufferData(a,w,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?w.subarray(c,c+b):b,d)},I:(a,b,c,d)=>{2<=Y.version?c&&P.bufferSubData(a,b,w,d,c):P.bufferSubData(a,b,w.subarray(d,d+c))},B:a=>P.checkFramebufferStatus(a),pa:(a,b,c,d)=>P.clearBufferfi(a,b,
c,d),y:(a,b,c)=>{P.clearBufferfv(a,b,pa,c>>2)},oa:(a,b,c)=>{P.clearBufferiv(a,b,x,c>>2)},h:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},db:a=>{P.compileShader(U[a])},Ba:(a,b,c,d,e,k,h,l)=>{2<=Y.version?P.Yb||!h?P.compressedTexImage2D(a,b,c,d,e,k,h,l):P.compressedTexImage2D(a,b,c,d,e,k,w,l,h):P.compressedTexImage2D(a,b,c,d,e,k,w.subarray(l,l+h))},Da:(a,b,c,d,e,k,h,l,m)=>{P.Yb?P.compressedTexImage3D(a,b,c,d,e,k,h,l,m):P.compressedTexImage3D(a,b,c,d,e,k,h,w,m,l)},wa:()=>{var a=yb(R),b=P.createProgram();
b.name=a;b.dc=b.bc=b.cc=0;b.pc=1;R[a]=b;return a},fb:a=>{var b=yb(U);U[b]=P.createShader(a);return b},s:a=>P.cullFace(a),gb:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.uc&&(P.uc=0),d==P.Yb&&(P.Yb=0))}},J:(a,b)=>{for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=sb[d];e&&(P.deleteFramebuffer(e),e.name=0,sb[d]=null)}},K:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):W||=1281}},Pa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=S[d];e&&
(P.deleteRenderbuffer(e),e.name=0,S[d]=null)}},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=V[d];e&&(P.deleteSampler(e),e.name=0,V[d]=null)}},n:a=>{if(a){var b=U[a];b?(P.deleteShader(b),U[a]=null):W||=1281}},Qa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=T[d];e&&(P.deleteTexture(e),e.name=0,T[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2];P.deleteVertexArray(tb[d]);tb[d]=null}},l:a=>P.depthFunc(a),m:a=>{P.depthMask(!!a)},c:a=>P.disable(a),ha:a=>{P.disableVertexAttribArray(a)},
vb:(a,b,c)=>{P.drawArrays(a,b,c)},wb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},A:(a,b)=>{for(var c=Fb[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];P.drawBuffers(c)},yb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},e:a=>P.enable(a),zb:a=>{P.enableVertexAttribArray(a)},C:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,S[d])},ba:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,T[d],e)},bb:(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,T[c],d,e)},r:a=>P.frontFace(a),Ma:(a,b)=>{X(a,
b,"createBuffer",Q)},D:(a,b)=>{X(a,b,"createFramebuffer",sb)},Ka:(a,b)=>{X(a,b,"createRenderbuffer",S)},xa:(a,b)=>{X(a,b,"createSampler",V)},Ga:(a,b)=>{X(a,b,"createTexture",T)},Sa:(a,b)=>{X(a,b,"createVertexArray",tb)},sa:(a,b)=>P.getAttribLocation(R[a],b?J(b):""),b:(a,b)=>Hb(a,b),ua:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(x[c>>2]=b)},F:(a,b,c)=>{if(c)if(a>=rb)W||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
x[c>>2]=a.length+1;else if(35719==b){if(!a.dc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.dc=Math.max(a.dc,P.getActiveUniform(a,b).name.length+1)}x[c>>2]=a.dc}else if(35722==b){if(!a.bc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.bc=Math.max(a.bc,P.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.bc}else if(35381==b){if(!a.cc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.cc=Math.max(a.cc,P.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.cc}else x[c>>2]=P.getProgramParameter(a,
b);else W||=1281},cb:(a,b,c,d)=>{a=P.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(x[c>>2]=b)},da:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(U[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=P.getShaderParameter(U[a],b):W||=1281},Ta:(a,b)=>{if(2>Y.version)return W||=1282,0;var c=vb[a];if(c)return 0>b||b>=c.length?(W||=1281,0):c[b];switch(a){case 7939:return c=Gb().map(Jb),c=vb[a]=c,0>b||
b>=c.length?(W||=1281,0):c[b];default:return W||=1280,0}},E:(a,b)=>{b=b?J(b):"";if(a=R[a]){var c=a,d=c.ac,e=c.Jc,k;if(!d){c.ac=d={};c.Ic={};var h=P.getProgramParameter(c,35718);for(k=0;k<h;++k){var l=P.getActiveUniform(c,k);var m=l.name;l=l.size;var q=Kb(m);q=0<q?m.slice(0,q):m;var u=c.pc;c.pc+=l;e[q]=[l,u];for(m=0;m<l;++m)d[u]=m,c.Ic[u++]=q}}c=a.ac;d=0;e=b;k=Kb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Jc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else W||=
1281;return-1},sb:(a,b,c)=>{for(var d=Fb[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];P.invalidateFramebuffer(a,d)},va:a=>{a=R[a];P.linkProgram(a);a.ac=0;a.Jc={}},Ra:(a,b)=>{3317==a?wb=b:3314==a&&(xb=b);P.pixelStorei(a,b)},x:(a,b)=>P.polygonOffset(a,b),ub:a=>P.readBuffer(a),Ha:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),H:(a,b,c)=>{P.samplerParameterf(V[a],b,c)},d:(a,b,c)=>{P.samplerParameteri(V[a],b,c)},ra:(a,b,c,d)=>P.scissor(a,b,c,d),eb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var h=(h=y[c+4*k>>2])?
J(h,d?y[d+4*k>>2]:void 0):"";e+=h}P.shaderSource(U[a],e)},ib:(a,b,c)=>P.stencilFunc(a,b,c),na:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),k:a=>P.stencilMask(a),hb:(a,b,c)=>P.stencilOp(a,b,c),ma:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Aa:(a,b,c,d,e,k,h,l,m)=>{if(2<=Y.version){if(P.Yb){P.texImage2D(a,b,c,d,e,k,h,l,m);return}if(m){var q=Lb(l);m>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,k,h,l,q,m);return}}if(m){q=Lb(l);var u=e*((xb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,
29847:4}[h-6402]||1)*q.BYTES_PER_ELEMENT+wb-1&-wb);m=q.subarray(m>>>31-Math.clz32(q.BYTES_PER_ELEMENT),m+u>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else m=null;P.texImage2D(a,b,c,d,e,k,h,l,m)},Ca:(a,b,c,d,e,k,h,l,m,q)=>{if(P.Yb)P.texImage3D(a,b,c,d,e,k,h,l,m,q);else if(q){var u=Lb(m);P.texImage3D(a,b,c,d,e,k,h,l,m,u,q>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,k,h,l,m,null)},Fa:(a,b,c)=>P.texParameteri(a,b,c),za:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,k)=>P.texStorage3D(a,
b,c,d,e,k),ta:(a,b)=>{var c=P,d=c.uniform1i;var e=P.Lc;if(e){var k=e.ac[a];"number"==typeof k&&(e.ac[a]=k=P.getUniformLocation(e,e.Ic[a]+(0<k?`[${k}]`:"")));a=k}else W||=1282,a=void 0;d.call(c,a,b)},i:a=>{a=R[a];P.useProgram(a);P.Lc=a},ka:(a,b)=>{P.vertexAttribDivisor(a,b)},la:(a,b,c,d,e,k)=>{P.vertexAttribPointer(a,b,c,!!d,e,k)},z:(a,b,c,d)=>P.viewport(a,b,c,d),_a:function(){f.Cc=a=>{0!=Sb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Cc)},Za:function(){f.Hc=
a=>{const b=a.clipboardData.getData("text");Qb(()=>{const c=Nb(b);Tb(c)})};window.addEventListener("paste",f.Hc)},Ya:function(a){f.od=[];a=a?J(a):"";a=document.getElementById(a);f.Dc=b=>{b.stopPropagation();b.preventDefault()};f.Ec=b=>{b.stopPropagation();b.preventDefault()};f.Fc=b=>{b.stopPropagation();b.preventDefault()};f.Gc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.pd=c;Ub(c.length);for(let e=0;e<c.length;e++)Qb(()=>{const k=Nb(c[e].name);Vb(e,k)});let d=0;b.shiftKey&&
(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Wb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Dc,!1);a.addEventListener("dragleave",f.Ec,!1);a.addEventListener("dragover",f.Fc,!1);a.addEventListener("drop",f.Gc,!1)},Va:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ab:function(a){a=a?J(a):"";f.$b=document.getElementById(a);f.$b||console.log("sokol_app.h: invalid target:"+a);f.$b.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},lb:function(){window.removeEventListener("beforeunload",f.Cc)},kb:function(){window.removeEventListener("paste",f.Hc)},jb:function(a){a=a?J(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.Dc);a.removeEventListener("dragleave",f.Ec);a.removeEventListener("dragover",f.Fc);a.removeEventListener("drop",f.Gc)},q:function(){f.$b&&f.$b.requestPointerLock&&f.$b.requestPointerLock()},Ua:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),
k=e.createImageData(a,b);k.data.set(w.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},pb:function(){return f.Wb?f.Wb.bufferSize:0},rb:function(a,b,c){f.Qb=null;f.Wb=null;"undefined"!==typeof AudioContext?f.Qb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.Qb=null,console.log("sokol_audio.h: no WebAudio support"));return f.Qb?(console.log("sokol_audio.h: sample rate ",
f.Qb.sampleRate),f.Wb=f.Qb.createScriptProcessor(c,0,b),f.Wb.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Xb(e);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let q=0;q<e;q++)m[q]=pa[(k>>2)+(h*q+l)]}}},f.Wb.connect(f.Qb.destination),a=()=>{f.Qb&&"suspended"===f.Qb.state&&f.Qb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},qb:function(){return f.Qb?f.Qb.sampleRate:0},ob:function(){const a=f.Qb;null!==a&&(f.Wb&&f.Wb.disconnect(),a.close(),f.Qb=null,f.Wb=null)},fa:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;ka=Z.Bb;c=ka.buffer;f.HEAP8=v=new Int8Array(c);f.HEAP16=ma=new Int16Array(c);f.HEAPU8=w=new Uint8Array(c);f.HEAPU16=na=new Uint16Array(c);f.HEAP32=x=new Int32Array(c);f.HEAPU32=y=new Uint32Array(c);f.HEAPF32=pa=new Float32Array(c);f.HEAPF64=z=new Float64Array(c);f.HEAP64=new BigInt64Array(c);f.HEAPU64=new BigUint64Array(c);L=Z.Db;sa.unshift(Z.Cb);B--;f.monitorRunDependencies?.(B);0==B&&C&&(c=C,C=null,c());return Z}B++;f.monitorRunDependencies?.(B);var b=
{a:Yb};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return r(`Module.instantiateWasm callback failed with error: ${c}`),!1}xa??=qa("pacman.wasm")?"pacman.wasm":f.locateFile?f.locateFile("pacman.wasm",n):n+"pacman.wasm";return a((await Aa(b)).instance)})();
var Tb=f.__sapp_emsc_onpaste=a=>(Tb=f.__sapp_emsc_onpaste=Z.Eb)(a),Sb=f.__sapp_html5_get_ask_leave_site=()=>(Sb=f.__sapp_html5_get_ask_leave_site=Z.Fb)(),Ub=f.__sapp_emsc_begin_drop=a=>(Ub=f.__sapp_emsc_begin_drop=Z.Gb)(a),Vb=f.__sapp_emsc_drop=(a,b)=>(Vb=f.__sapp_emsc_drop=Z.Hb)(a,b),Wb=f.__sapp_emsc_end_drop=(a,b,c)=>(Wb=f.__sapp_emsc_end_drop=Z.Ib)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,h,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Jb)(a,b,c,d,e,k,h,l);
var Zb=f._main=(a,b)=>(Zb=f._main=Z.Kb)(a,b),Xb=f.__saudio_emsc_pull=a=>(Xb=f.__saudio_emsc_pull=Z.Lb)(a),N=a=>(N=Z.Mb)(a),Pb=a=>(Pb=Z.Nb)(a),Mb=a=>(Mb=Z.Ob)(a),Ob=()=>(Ob=Z.Pb)();function $b(a=[]){var b=Zb;a.unshift(ea);var c=a.length,d=Mb(4*(c+1)),e=d;a.forEach(h=>{y[e>>2]=Nb(h);e+=4});y[e>>2]=0;try{var k=b(c,d);Ma(k)}catch(h){Na(h)}}
function ac(a=da){function b(){f.calledRun=!0;if(!t){Ca(sa);Ca(ta);f.onRuntimeInitialized?.();f.noInitialRun||$b(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ua.unshift(c)}Ca(ua)}}if(0<B)C=ac;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Ca(ra);0<B?C=ac:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();ac();
